config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  get '/pages/:page' => 'pages#show'
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
  devise_scope :user do get '/users/sign_out' => 'devise/sessions#destroy' end

  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]

    post :show, on: :member
  end
  resources :users, only: [:show, :edit, :update]
end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :user
  has_many :comments
  has_many :subscriptions
  has_many :subscribers, through: :subscriptions, source: :user
  has_many :photos

  validates :user, presence: true
  validates :title, presence: true, length: { maximum: 255 }
  validates :address, presence: true
  validates :datetime, presence: true

  def visitors
    (subscribers + [user]).uniq
  end

  def pincode_valid?(pin2check)
    pincode == pin2check
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_event, except: [:index, :new, :create]
  before_action :password_guard!, only: [:show]
  after_action :verify_authorized, only: [:edit, :update, :destroy, :show]

  def index
    @events = Event.all
  end

  def show
    authorize @event

    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
    @new_photo = @event.photos.build(params[:photo])
  end

  def new
    @event = current_user.events.build
    authorize @event
  end

  def edit
    authorize @event
  end

  def create
    @event = current_user.events.build(event_params)

    authorize @event

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: I18n.t('controllers.events.created') }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize @event

    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: I18n.t('controllers.events.updated') }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    authorize @event

    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: I18n.t('controllers.events.deleted') }
    end
  end

  private

  def password_guard!
    return  true if @event.pincode.blank?
    return  true if signed_in? && current_user == @event.user

    if params[:pincode].present? && @event.pincode_valid?(params[:pincode])
      cookies.permanent["events_#{@event.id}_pincode"] = params[:pincode]
    end

    unless @event.pincode_valid?(cookies.permanent["events_#{@event.id}_pincode"])
      flash.now[:alert] = I18n.t('controllers.events.wrong_pincode') if params[:pincode].present?

      render 'password_form'
    end
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :address, :description, :datetime, :pincode)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="col-sm-6 col-md-4">
  <div class="thumbnail">
    <%= content_tag 'div', '', class: 'event-background',
                    style: "background-image: url(#{asset_path('event_thumb.jpg')})" %>
    <div class="thumbnail-inner event-info-inner">
      <div class="caption">
        <div class="event-description">
          <h3><%= link_to event.title, event_path(event) %></h3>
          <h3><small><%= l event.datetime, format: :short %></small></h3>
          <div class="mt-2"><%= event.address %></div>
        </div>
        <div>
          <% event.visitors.each do |user| %>
            <%= image_tag user_avatar_thumb(user), class: 'img-icon', title: user.name %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <%= render partial: 'partials/form_errors', locals: {model: @event} %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :datetime %>
    <p><input type='text' class="datepicker-here" id="datetime" name="event[datetime]" data-timepicker="true" data-inline="true" data-position="right top" /></p>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :pincode %>
    <%= f.text_field :pincode, class: 'form-control' %>
  </div>


  <div class="actions">
    <%= f.submit 'Сохранить', class: 'btn btn-primary' %>
    или <%= link_to 'вернуться', :back %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Редактирование события</h1>

<%= render 'form', event: @event %>

app/views/events/index.html.erb
<h1>События</h1>
<div class="mb-2 mt-2">
  <% if policy(Event).create? %>
  <%= link_to 'Создать событие', new_event_path, class: 'btn btn-success' %>
  <% end %>
</div>
<div class="row mb-2">
  <%= render partial: 'events/event', collection: @events %>
</div>

app/views/events/new.html.erb
<h1>Новое событие</h1>

<div class="row">
  <div class="col-md-6 buffer-top">
    <%= render 'form' %>
  </div>
</div>

app/views/events/password_form.html.erb
<h1>Доступ только по пин-коду</h1>

<%= form_tag('', method: 'post') do |f| %>
  <div class="form-group">
    <%= label 'Пин-код', :pincode %>
    <%= text_field_tag :pincode, params[:pincode], class: 'form-control' %>
  </div>

  <div class="actions">
    <%= submit_tag %>
  </div>
<% end %>

<%= link_to 'На главную', events_path %>

app/views/events/show.html.erb
<div class="event">
  <div class="event-info row pl-md-3">
    <div class="col-md-12">
      <%= content_tag 'div', '',
        class: 'event-background',
        style: "background-image: url(#{event_photo(@event)})"
      %>
      <div class="event-info-inner row">
        <div class="col-md-6 col-12">
          <div class="event-description">
            <h1><%= @event.title %></h1>
            <h3><%= l @event.datetime, format: :short %></h3>
            <h3><small><%= link_to @event.address,
                                   "https://yandex.ru/maps/?text=#{@event.address}" %></small></h3>
            <p><%= @event.description %></p>
          </div>
          <% if current_user_can_edit?(@event) %>
            <div class="row mt-2">
                <div class="mr-2 ml-2">
                  <%= link_to 'Изменить', edit_event_path(@event),
                              class: 'btn btn-primary mb-2' %>
                </div>
                <div>
                  <%= link_to 'Удалить', @event, method: :delete, data: { confirm: t('messages.sure?') },
                              class: 'btn btn-danger mb-2' %>
                </div>
            </div>
          <% end %>
        </div>
        <div class="col-md-6 col-12">
          <div id="map" class="mt-3 mb-3"
               data-address="<%= @event.address %>"
               style="width: 100%; height: 100%; min-height: 10rem;">
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8 col-12">
      <div class="event-photos-form">
        <%= render partial: 'photos/form', locals: { photo: @new_photo || @event.photos.build } %>
      </div>
      <div class="event-comments mt-2">
        <%= render partial: 'comments/form',locals: {comment: @new_comment || @event.comments.build} %>
        <div class="mt-2 mb-2" id="event-comments">
          <%= render partial: 'comments/comment', collection: @event.comments.except(@new_comment).order("created_at DESC") %>
        </div>
      </div>
    </div>
    <div class="col-md-4 col-12">
      <div class="event-owner">
        <h5>Зовет:</h5>
        <p><%= render partial: 'users/user', object: @event.user %></p>
      </div>
      <div class="event-subscriptions">
        <h5>Пойдут:</h5>
        <div>
          <p>
            <%= render partial: 'subscriptions/subscription',
                       collection: @event.subscriptions.except(@new_subscription) %>
          </p>
        </div>
      </div>
      <% if @event.user != current_user %>
        <div class="event-subscription-form">
          <h5>Я пойду:</h5>
          <div>
            <%= render partial: 'subscriptions/form', locals: {
                subscription: @new_subscription || @event.subscriptions.build
            } %>
          </div>
        </div>
      <% end %>
      <div class="event-photos">
        <div class="event-photos-gallery">
          <%= render partial: 'photos/photo', collection: @event.photos.except(@new_photo) %>
        </div>
      </div>
    </div>
  </div>
</div>